export const countryMappings = {
    'Россия': 'Russia',
    'США': 'United States of America',
    'СССР': 'USSR',
    'Франция': 'France',
    'Великобритания': 'United Kingdom',
    'Германия': 'Germany',
    'Италия': 'Italy',
    'Япония': 'Japan',
    'Китай': 'China',
    'Индия': 'India',
    'Испания': 'Spain',
    'Канада': 'Canada',
    'Австралия': 'Australia',
    "Австрия": 'Austria',
    "Беларусь": 'Belarus',
    "Бельгия": 'Belgium',
    "Бразилия": 'Brazil',
    "Венгрия": 'Hungary',
    "Гамбия": 'Gambia',
    "Гонконг": 'Hong Kong',
    "Дания": 'Denmark',
    "Иордания": 'Jordan',
    "Корея Южная": 'South Korea',
    "Латвия": 'Latvia',
    "Мальта": 'Malta',
    "Марокко": 'Morocco',
    "Мексика": 'Mexico',
    "Нидерланды": 'Netherlands',
    "Новая Зеландия": 'New Zeland',
    "Норвегия": 'Nordway',
    "ОАЭ": 'United Arab Emirates',
    "Польша": 'Poland',
    "Сербия": 'Serbia',
    "Таиланд": 'Thailand',
    "Финляндия": 'Finland',
    "Чехия": 'Czechia',
    "Швейцария": 'Switzerland',
    "Швеция": 'Sweden',
  };